In [ ]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

cols=  [i for i in list(df.columns) if df[i].dtypes=='object']
for col in cols:
  df[col] = le.fit_transform(df[col])

In [ ]:
x= df.iloc[:, 3:13]
y = df.Exited

In [ ]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state=30)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_test

array([[-1.17268106,  0.30607902,  0.90704943, ...,  0.64395441,
         0.97067965,  0.52266327],
       [ 0.49157241,  0.30607902,  0.90704943, ..., -1.55290497,
        -1.030206  , -0.11547355],
       [ 0.19180004, -0.90371948,  0.90704943, ..., -1.55290497,
         0.97067965,  1.26702948],
       ...,
       [-0.71785403, -0.90371948,  0.90704943, ...,  0.64395441,
        -1.030206  ,  1.71950199],
       [ 0.60527917, -0.90371948,  0.90704943, ...,  0.64395441,
        -1.030206  , -0.77248791],
       [ 1.94908631, -0.90371948, -1.10247575, ...,  0.64395441,
         0.97067965, -0.54830204]])

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import ReLU, ELU, PReLU
from tensorflow.keras.layers import Dropout

In [ ]:
model = Sequential()
model.add(Dense(units=11, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units= 7,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=6,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=1,activation='sigmoid'))

In [ ]:
model.compile(
    optimizer='adam', loss='binary_crossentropy',metrics=['accuracy']
)

In [ ]:
import tensorflow
early_stopping = tensorflow.keras.callbacks.EarlyStopping(
    monitor="accuracy",
    min_delta=0,
    patience=0,
    verbose=0,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [ ]:
model_history=model.fit(x_train,y_train,validation_split=0.33, batch_size=10,epochs=100,callbacks= early_stopping)

Epoch 1/100
536/536 [==============================] - 3s 4ms/step - loss: 0.5185 - accuracy: 0.7959 - val_loss: 0.4659 - val_accuracy: 0.7963
Epoch 2/100
536/536 [==============================] - 2s 3ms/step - loss: 0.4835 - accuracy: 0.8015 - val_loss: 0.4494 - val_accuracy: 0.7970
Epoch 3/100
536/536 [==============================] - 1s 3ms/step - loss: 0.4607 - accuracy: 0.8035 - val_loss: 0.4403 - val_accuracy: 0.7993
Epoch 4/100
536/536 [==============================] - 2s 4ms/step - loss: 0.4583 - accuracy: 0.8015 - val_loss: 0.4384 - val_accuracy: 0.8001